version = 0.1

[default.deploy.parameters]
stack_name = "ratemyrickshaw"
resolve_s3 = true
s3_prefix = "ratemyrickshaw"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"prod\""
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
